version: '3.8'

services:
  main:
    build:
      context: ./demo/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_NAME: DB
      MYSQL_ROOT_PASSWORD: 12341234
    depends_on:
      - db
      - redis
    networks:
      - ci-network
    volumes:
      - demo-data:/app

  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: DB
    ports:
      - "5432:5432"
    networks:
      - ci-network
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    networks:
      - ci-network

  tester:
    build:
      context: ./devopsunittest
      dockerfile: Dockerfile
    depends_on:
      - main
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge

volumes:
  demo-data:
  db-data:
